export const ES_TEXT = {
  appName: "Texas Counties Division Patrol LLC",
  header: {
    notificationsAria: "Notificaciones",
    userMenuAria: "Abrir menú de usuario",
  },
  sidebar: {
    navigationLabel: "Navegación",
  },
  menu: {
    dashboard: "Panel",
    clients: "Clientes",
    guards: "Guardias",
    users: "Usuarios",
    properties: "Propiedades",
  },
  common: {
    notFoundTitle: "Contenido no encontrado",
    notFoundDescription: "Selecciona una opción del menú.",
  },
  dashboard: {
    title: "Resumen del Panel",
    chartHoursTitle: "Horas trabajadas por mes",
    chartCostsTitle: "Costos por mes",
    series: {
      priceTotal: "Precio Total",
      fuelCost: "Costo Gasolina",
      guardSalary: "Salario Guardia",
    },
    upcomingShifts: {
      title: "Próximos turnos",
      headers: { guard: "Guardia", location: "Lugar", date: "Fecha" },
    },
  },
  clients: {
    title: "Gestión de Clientes",
    table: {
      title: "Lista de Clientes",
      add: "Agregar",
      headers: {
        name: "Nombre",
        properties: "# Propiedades",
        totalPrice: "Precio Total ($)",
        expenses: "Gastos ($)",
        fuel: "Gasolina ($)",
        actions: "Acciones",
      },
      actionEdit: "Editar {name}",
      actionDelete: "Eliminar {name}",
    },
    errorLoading: "Error al cargar clientes",
    propertiesError: "Error al cargar propiedades",
    list: {
      title: "Lista de Clientes",
      addClient: "Agregar Cliente",
      searchPlaceholder: "Buscar clientes...",
      headers: {
        clientName: "Nombre del Cliente",
        email: "Correo",
        phone: "Teléfono",
        balance: "Saldo",
        status: "Estado",
        actions: "Acciones",
      },
      statusActive: "Activo",
      statusInactive: "Inactivo",
    },
    loading: "Cargando clientes...",
    selectPrompt: "Selecciona un cliente para ver sus propiedades.",
    propertiesLoading: "Cargando propiedades...",
    properties: {
      title: "Propiedades de {clientName}",
      headers: {
        name: "Nombre",
        price: "Precio ($)",
        expenses: "Gastos ($)",
        hours: "Horas/Mes",
        fuel: "Gasolina ($)",
        actions: "Acciones",
      },
       pageSizeLabel: "Items por página",
      actionEdit: "Editar {name}",
      actionDelete: "Eliminar {name}",
    },
  },
  guards: {
    title: "Gestión de Guardias",
    selectPrompt: "Selecciona un guardia para ver sus turnos.",
    weeklyMaxNote: "Nota: los totales se calculan sumando los turnos (hours × pricePerHour). Máx. semanal configurado a {hours}h.",
    table: {
      title: "Lista de Guardias",
      add: "Agregar",
      headers: {
        name: "Nombre",
        totalHours: "Horas Totales",
        totalSalary: "Salario Total ($)",
        actions: "Acciones",
      },
       pageSizeLabel: "Items por página",
      actionEdit: "Editar guardia {name}",
      actionDeleteConfirm: "¿Eliminar guardia {name}?",
      actionDelete: "Eliminar guardia {name}",
      confirmLabel: "Confirmar",
      deleteSuccess: "Guardia {name} eliminado",
    },
  },
  users: {
    title: "Gestión de Usuarios",
    loading: "Cargando usuarios...",
    selectPrompt: "Selecciona un usuario para ver y editar sus permisos.",
    noPermissions: "Sin permisos",
    table: {
      title: "Lista de Usuarios",
      add: "Agregar",
      searchPlaceholder: "Buscar...",
      headers: {
        username: "Usuario",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo",
        permissions: "Permisos",
        actions: "Acciones",
      },
    },
  },
  properties: {
    title: "Gestión de Propiedades",
    table: {
      title: "Lista de Propiedades",
      add: "Agregar",
      searchPlaceholder: "Buscar...",
      headers: {
        owner: "Propietario",
        name: "Nombre",
        address: "Dirección",
        serviceTypes: "Tipos de Servicio",
        monthlyRate: "Tarifa Mensual",
        totalHours: "Horas Totales",
        startDate: "Fecha Inicio",
        actions: "Acciones",
      },
       pageSizeLabel: "Items por página",
      actionEdit: "Editar {name}",
      actionDelete: "Eliminar {name}",
    },
    form: {
      createTitle: "Crear Propiedad",
      editTitle: "Editar Propiedad",
      fields: {
        ownerUser: "Owner (user id)",
        ownerPhone: "Teléfono propietario",
        name: "Nombre",
        address: "Dirección",
        typesOfService: "Tipos de Servicio",
        monthlyRate: "Tarifa Mensual",
        contractStartDate: "Fecha de inicio del contrato",
        totalHours: "Horas Totales",
      },
      buttons: {
        cancel: "Cancelar",
        create: "Crear",
        save: "Guardar",
        delete: "Eliminar",
      },
    },
  },
  accountMenu: {
    language: "Idioma",
    english: "Inglés",
    spanish: "Español",
    settings: "Configuración",
    support: "Soporte",
    logout: "Cerrar sesión",
  },
  logoutDialog: {
    title: "Confirmar cierre de sesión",
    description:
      "¿Seguro que quieres cerrar sesión? Necesitarás iniciar sesión nuevamente para acceder al panel.",
    cancel: "Cancelar",
    confirm: "Cerrar sesión",
    successToast: "Sesión cerrada correctamente",
  },
  login: {
    title: "Iniciar sesión",
    description: "Ingresa tu usuario y contraseña para acceder a tu cuenta.",
    usernameLabel: "Usuario",
    usernamePlaceholder: "usuario",
    passwordLabel: "Contraseña",
    submit: "Ingresar",
    submitting: "Iniciando...",
    errorDefault: "Credenciales incorrectas. Intenta de nuevo.",
  },
} as const
