export const EN_TEXT = {
  appName: "Texas Counties Division Patrol LLC",
  header: {
    notificationsAria: "Notifications",
    userMenuAria: "Toggle user menu",
  },
  sidebar: {
    navigationLabel: "Navigation",
  },
  menu: {
    dashboard: "Dashboard",
    clients: "Clients",
    guards: "Guards",
    users: "Users",
    properties: "Properties",
    shifts: "Shifts",
    services: "Services",
    notes: "Notes",
  },

  pagination: {
    goToPlaceholder: "Go to...",
    ariaFirst: "Go to first page",
    ariaPrev: "Previous page",
    ariaNext: "Next page",
    ariaLast: "Go to last page",
    inputAriaLabel: "Go to specific page",
    pageInfo: "{current} of {total}",
  },

  table: {
    noMatch: "No match",
    noResults: "No results found for \"{search}\"",
    noData: "No data available",
    items: "items",
  },

  common: {
    notFoundTitle: "Content not found",
    notFoundDescription: "Select an option from the menu.",
    loading: "Loading...",
    yes: "Yes",
    no: "No",
  },

  actions: {
     add: "Add",
    refresh: "Refresh",
    save: "Save",
    cancel: "Cancel",
    cancelEdit: "Cancel Edit",
    edit: "Edit",
    delete: "Delete",
    reset: "Reset",
    close: "Close",
    actions: "Actions",
    create: "Create",
    copy: "Copy",
    copySuccess: "Copied to clipboard",
    copyError: "Could not copy",
    saving: "Saving...",
    deleting: "Deleting...",
    view: "View",
    show: "Show",
  },

 weapons: {
    panel: {
      title: "Assigned Weapons",
      add: "Add Weapon",
    },
    create: {
      title: "Create Weapon",
    },
    delete: {
      title: "Delete Weapon",
      confirm: "Are you sure you want to delete {name}?",
    },
    form: {
      fields: {
        serialNumber: "Serial Number",
        model: "Model",
      },
      buttons: {
        create: "Create",
        saving: "Creating...",
        delete: "Delete",
        deleting: "Deleting...",
        apply: "Apply",
        applying: "Applying...",
      },
    },
    errors: {
      missingGuard: "Select a guard",
      missingSerial: "Serial required",
      missingModel: "Model required",
      createFail: "Error creating weapon",
      deleteFail: "Error deleting weapon",
    }, 
    messages: {
      created: "Weapon created",
      updated: "Weapon updated",
      deleted: "Weapon deleted",
    },
    table: {
      actionDeleteConfirm: "Delete weapon {name}?",
      actionDelete: "Delete weapon {name}",
    },
  },

  clients: {
    title: "Clients Management",
    table: {
      title: "Clients List",
      add: "Add",
      headers: {
        name: "Name",
        properties: "# Properties",
        totalPrice: "Total Price ($)",
        expenses: "Expenses ($)",
        fuel: "Fuel ($)",
        actions: "Actions",
      },
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
      notesTitle: "Notes for client",
    },
    list: {
      title: "Clients List",
      addClient: "Add Client",
      searchPlaceholder: "Search clients...",
      headers: {
        clientName: "Client Name",
        email: "Email",
        phone: "Phone",
        balance: "Balance",
        status: "Status",
        actions: "Actions",
      },
      statusActive: "Active",
      statusInactive: "Inactive",
    },

    form: {
      createTitle: "Create Client",
      fields: {
        username: "Username",
        firstName: "First name *",
        lastName: "Last name *",
        email: "Email *",
        phone: "Phone",
        address: "Address",
        billingAddress: "Billing address",
      },
      placeholders: {
        address: "Client's primary address",
        billingAddress: "Address used for invoicing",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
      },
      validation: {
        firstNameRequired: "First name is required",
        lastNameRequired: "Last name is required",
        emailRequired: "Email is required",
      },
      success: "Client created",
    },

    properties: {
      title: "Properties of {clientName}",
      headers: {
        name: "Name",
        price: "Price ($)",
        expenses: "Expenses ($)",
        hours: "Hours/Month",
        fuel: "Fuel ($)",
        actions: "Actions",
      },
      pageSizeLabel: "Rows per page",
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
    },
    loading: "Loading clients...",
    selectPrompt: "Select a option to view its properties.",
    propertiesLoading: "Loading properties...",
    errorLoading: "Error loading clients",
    propertiesError: "Error loading properties",
    clientDetails: {
      labels: {
        clientId: "Client #",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone",
        balance: "Balance",
        createdAt: "Created Date",
        updatedAt: "Last Updated",
        primaryAddress: "Primary Address",
        billingAddress: "Billing Address",
      },
      status: {
        active: "Active",
        inactive: "Inactive",
      },
      sections: {
        addresses: "Addresses",
      },
      buttons: {
        close: "Close",
      },
      tooltips: {
        openInWhatsapp: "Open in WhatsApp",
      },
    },
  },

  properties: {
    title: "Properties Management",
    // ADDED: title used by the shifts header; supports {propertyName} and {propertyId}
    shiftsTitle: "Shifts — {propertyName}", /* ADDED */
    table: {
      title: "Properties List",
      add: "Add",
      searchLabel: "Search properties",
      searchPlaceholder: "Search properties...",
      headers: {
        owner: "Owner",
        alias: "Nick",
        name: "Name",
        address: "Address",
        serviceTypes: "Service Types",
        monthlyRate: "Monthly Rate",
        totalHours: "Hours",
        actions: "Actions",
      },
      pageSizeLabel: "Rows per page",
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
      notesTitle: "Notes for property",
    },
    form: {
      editTitle: "Edit Property",
      createTitle: "Create Property",
      fields: {
        ownerUser: "Owner ",
        ownerPhone: "Owner phone",
        name: "Name",
        alias: "Alias",
        address: "Address",
        typesOfService: "Service Types",
        monthlyRate: "Monthly Rate",
        contractStartDate: "Contract Start Date",
        totalHours: "Hours",
        description: "Description",
      },
      placeholders: {
        owner: "Search client by name/username...",
        name: "Property name",
        alias: "Alias or alternative name",
        address: "Property address",
        monthlyRate: "$0.00",
        totalHours: "0",
        description: "Description, notes, etc.",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
        save: "Save",
        saving: "Saving...",
        delete: "Delete",
      },
      searchingText: "Searching...",
      noResultsText: "No results",
      ownerHelp: "Select the owner client.",
      serviceTypesTitle: "Service Types",
      loadingTypesText: "Loading service types",
      noTypesText: "No types available",
      success: "Property updated",
      createSuccess: "Property created successfully",
      errorUpdate: "Error updating property",
      errorRefresh: "Failed to refresh properties",
      delete: {
        title: "Delete Property",
        confirm: "Are you sure you want to delete {name}?",
        note: "This action cannot be undone.",
        button: "Delete",
        deleting: "Deleting...",
        success: "Property deleted successfully",
        error: "Error deleting property",
        cancel: "Cancel",
        errorRefresh: "Failed to refresh properties",
      },
      viewer: "Viewer",
      editor: "Editor",
      admin: "Admin",
      full: "Full",
    },
    help: "Check to grant, uncheck to revoke.",
    ownerDetails: {
      title: "Owner",
      username: "Username",
      statusActive: "Active",
      statusInactive: "Inactive",
      labels: {
        email: "Email",
        phone: "Phone",
        address: "Address",
        created: "Created",
        updated: "Updated",
      },
      buttons: {
        refresh: "Refresh",
      },
      messages: {
        noData: "No owner data found.",
        errorLoading: "Error loading owner:",
      },
    },
    propertyDetails: {
      title: "Property",
      labels: {
        name: "Name",
        alias: "Alias/Nick",
        address: "Address",
        contractStartDate: "Contract Start Date",
        created: "Created",
        updated: "Updated",
        description: "Description",
        owner: "Owner",
        ownerEmail: "Owner Email",
        ownerPhone: "Owner Phone",
      },
      sections: {
        ownerInfo: "Owner Information",
      },
      buttons: {
        close: "Close",
      },
    },
  },

  guards: {
    title: "Guards Management",
    selectPrompt: "Select a guard to view their shifts.",
    weeklyMaxNote: "Note: totals are calculated by summing shifts (hours × pricePerHour). Weekly max set to {hours}h.",
    table: {
      title: "Guards List",
      add: "Add Guard",
      addButton: "Add Guard",
      searchPlaceholder: "Search guards...",
      headers: {
        name: "Name",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone",
        ssn: "SSN / ID",
        birthdate: "Birth Date",
        totalHours: "Hours",
        totalSalary: "Total Salary ($)",
        actions: "Actions",
      },
      ssnHidden: "******",
      pageSizeLabel: "Rows per page",
      actionEdit: "Edit guard {name}",
      actionDeleteConfirm: "Delete guard {name}?",
      actionDelete: "Delete guard {name}",
      confirmLabel: "Confirm",
      deleteSuccess: "Guard {name} deleted",
      notesTitle: "Notes for guard",
    },
    errorLoading: "Error loading guards",
    form: {
      createTitle: "Create Guard",
      editTitle: "Edit Guard",
      fields: {
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone",
        ssn: "SSN / ID",
        birthdate: "Birthdate",
        address: "Address",
      },
      validation: {
        invalidEmail: "Invalid email",
        firstNameRequired: "First name is required",
        lastNameRequired: "Last name is required",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
        save: "Save",
        saving: "Saving...",
        delete: "Delete",
      },
      actions: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
        save: "Save",
        saving: "Saving...",
        delete: "Delete",
        showSsn: "Show"
      }
    },
    tariffs: {
      title: "Tariffs for {name}",
      assignedLabel: "Assigned tariffs",
      assignedNote: "One tariff per property. Click to edit.",
      count: "{count} property(ies) with a tariff",
      empty: "This guard has no assigned tariffs.",
      rateHeader: "Tariff",
      activeHeader: "Active",
      flag: "⚑ Tariff",
      active: "Active",
      inactive: "Inactive",
      selectedPropertyLabel: "Selected property",
      noneSelected: "No property selected",
      rateLabel: "Rate per hour",
      ratePlaceholder: "E.g. 15.00",
      activeLabel: "Active",
      changeProperty: "Change property",
      create: "Create tariff",
      update: "Update tariff",
      saving: "Saving...",
      note: "Note: if the property already has tariff, selecting it will load it for editing; otherwise you'll create a new one.",
      validation: {
        propertyRequired: "Select a property first",
        rateRequired: "Rate is required",
        rateInvalid: "Rate must be a valid number",
        rateNegative: "Rate cannot be negative",
        rateTooHigh: "Rate cannot be greater than $1000"
      },
      actions: {
        create: "create",
        update: "update"
      },
      confirmSave: "Are you sure you want to {action} this ${rate} tariff for {property}?",
      confirmCancelEdit: "Are you sure you want to cancel editing? Unsaved changes will be lost.",
      confirmDelete: "Are you sure you want to delete the tariff for {property}?",
      exists: "A tariff already exists for this property. It will be loaded for editing.",
      createSuccess: "Tariff created successfully",
      updateSuccess: "Tariff updated successfully",
      deleteSuccess: "Tariff deleted successfully",
      saveError: "Error saving tariff. Please check the data and try again.",
      deleteError: "Error deleting tariff. Please try again."
    },
  },

  users: {
    title: "User Management",
    editTitle: "Edit User",
    saveChanges: "Save changes",
    cancel: "Cancel",
    loading: "Loading users...",
    selectPrompt: "Select a user to view and edit their permissions.",
    noPermissions: "No permissions",
    permissionsTitle: "Permissions by resource",
    userTypes: {
      superuser: "Superuser",
      staff: "Staff",
      user: "User",
    },
    accessTypes: {
      viewer: "Viewer",
      manager: "Manager",
      admin: "Admin",
    },
    table: {
      title: "Users List",
      add: "Add User",
      searchPlaceholder: "Search...",
      perPage: "per page",
      headers: {
        username: "Username",
        firstName: "First name",
        lastName: "Last name",
        email: "Email",
        permissions: "Status",
        actions: "Actions",
      },
      notesTitle: "Notes for user",
    },
    form: {
      createTitle: "Create User",
      editTitle: "Edit User",
      fields: {
        username: "Username",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
      },
      validation: {
        usernameRequired: "Username is required",
        firstNameRequired: "First name is required",
        lastNameRequired: "Last name is required",
        emailRequired: "Email is required",
        emailInvalid: "Invalid email format",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 6 characters",
        passwordMatch: "Passwords do not match",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
        save: "Save",
        saving: "Saving...",
        delete: "Delete",
      },
      createSuccess: "User created",
    },
    permissionsHelp: "Permissions are applied as resource.action.",
    permissionsTable: {
      title: "User Permissions",
      subtitle: "Manage permissions and access for",
      refresh: "Refresh",
      refreshSuccess: "Options reloaded",
      refreshError: "Error reloading options",
      save: "Save changes",
      saving: "Saving...",
      saveSuccess: "Changes saved successfully",
      saveError: "Error saving changes",
      loadingOptions: "Loading options and permissions…",
      noOptions: "No permission options available.",
      loadError: "Error loading permissions/user",
      grantError: "Error granting permissions",
      revokeError: "Error revoking permissions",
      grantPropertyError: "Error granting property access",
      updatePropertyError: "Error updating access",
      revokePropertyError: "Error revoking access",
      grantReason: "Granted from UI",
      revokeReason: "Revoked from UI",
      updateReason: "Updated from UI",
      resourcePermissions: {
        title: "Permissions by resource",
        subtitle: "Configure specific permissions for each resource type",
        note: "Changes are applied with grant/revoke by resource/action using administrative endpoints.",
      },
      propertyAccess: {
        title: "Property Access",
        subtitle: "Manage specific access to each property in the system",
        searchPlaceholder: "Search...",
        searchAriaLabel: "Search",
        noProperties: "No properties found.",
        noMatches: "No matches found.",
        note: "Check to grant, uncheck to revoke. Access type is sent in the request.",
      },
    },
  },

  permissions: {
    resources: {
      guard: { label: "Guard" },
      expense: { label: "Expense" },
      shift: { label: "Shift" },
      client: { label: "Client" },
    },
    actions: {
      create: "Create",
      read: "Read",
      update: "Update",
      delete: "Delete",
      approve: "Approve",
      assign: "Assign",
    },
  },

  accountMenu: {
    language: "Language",
    english: "English",
    spanish: "Español",
    settings: "Settings",
    support: "Support",
    logout: "Logout",
  },

  logoutDialog: {
    title: "Confirm logout",
    description: "Are you sure you want to log out? You will need to sign in again to access the dashboard.",
    cancel: "Cancel",
    confirm: "Logout",
    successToast: "Logged out successfully",
  },

  login: {
    title: "Login",
    description: "Enter your username and password to access your account.",
    usernameLabel: "Username",
    usernamePlaceholder: "username",
    passwordLabel: "Password",
    submit: "Sign in",
    submitting: "Signing in...",
    errorDefault: "Invalid credentials. Please try again.",
  },

  shifts: {
    create: {
      title: "Create Shift",
      propertyPlaceholder: "Property ID (number)",
      searchGuardPlaceholder: "Search guard by name or email...",
      searchPropertyPlaceholder: "Search properties...",
      searching: "Searching...",
      noMatches: "No matches",
      clear: "Clear",
      selectPropertyFirst: "Select a property first",
      selectService: "-- Select service --",
      loadingServices: "Loading services...",
      noServicesAvailable: "No services available",
      plannedStart: "Planned Start",
      plannedEnd: "Planned End",
      overlapDetected: "Overlap Detected",
      isArmed: "Is armed",
      selectWeapon: "Select weapon (from guard) — optional",
      noWeapons: "(no weapons)",
      loadingWeapons: "Loading weapons...",
      otherManualSerial: "Other / Manual serial",
      weaponSerialPlaceholder: "Serial number (manual or selected)",
      selectedSerial: "Selected serial: {serial}",
      manualSerialHelp: "You can enter a manual serial if the weapon is not in the list.",
      weaponModel: "Model",
      weaponSerial: "Serial",
    },
    edit: {
      title: "Edit Shift",
    },
    delete: {
      title: "Delete Shift",
      confirm: "Are you sure you want to delete this shift?",
      hardDeleteLabel: "Hard delete (permanently remove)",
    },
    show: {
      title: "Shift Details",
      subtitle: "Scrollable list of shifts",
      open: "View shifts",
    },
    // ADDED: search placeholder for shifts header
    searchPlaceholder: "Search guards...", /* ADDED */
    noShiftsInRange: "No shifts/guards in the selected range.",
    errors: {
      
      missingDates: "Start and end are required",
      endBeforeStart: "End must be after start",
      missingProperty: "Property ID required",
      missingGuard: "Guard ID required",
      missingService: "Service required",
      createFailed: "Could not create shift",
      fetchFailed: "Could not load shift",
      updateFailed: "Could not update shift",
      deleteFailed: "Could not delete shift",
      noShift: "No shift loaded",
    },
    messages: {
      created: "Shift created",
      updated: "Shift updated",
      deleted: "Shift deleted",
      softDeleted: "Shift soft-deleted",
    },
  },

  services: {
    title: "Services Management",
    add: "Add",
    addButton: "Add",
    searchPlaceholder: "Search services...",
    errorLoading: "Error loading services",
    table: {
      title: "Services List",
      add: "Add",
      searchPlaceholder: "Search services...",
      headers: {
        name: "Name",
        guard: "Guard",
        property: "Property",
        totalHours: "Total Hrs",
        rate: "Amount",       // changed label text to "Amount"
        monthlyBudget: "Monthly",
        recurrent: "Recurrent",
        isActive: "Active",
        actions: "Actions",
      },
      pageSizeLabel: "Rows per page",
     
    recurrentYes: "Yes",
    recurrentNo: "No",
      activeLabel: "Yes",
      inactiveLabel: "No",
      notesTitle: "Notes for service",
      notesButton: "Notes",
      notesAria: "View service notes",
      addNoteButton: "Add note",
      addNoteAria: "Add note for service",
    },
    create: {
      title: "Create Service",
    },
    edit: {
      title: "Edit Service",
    },
    delete: {
      title: "Delete Service",
      confirm: "Are you sure you want to delete service \"{name}\"?",
    },
    show: {
      title: "Service details",
    },
    placeholders: {
      guard: "Type to search guards (e.g. 'Pedro')",
      property: "Type to search properties (address/name)",
      contractStartDate: "YYYY-MM-DD",
      startTime: "HH:MM",
      endTime: "HH:MM",
      schedule: "YYYY-MM-DD",
    },
    fields: {
      name: "Name",
      description: "Description",
      guard: "Guard",
      assignedProperty: "Property",
      rate: "Amount",       // changed
      recurrent: "Recurrent",
      monthlyBudget: "Monthly Budget",
      schedule: "Schedule",
      startTime: "Start",
      endTime: "End",
      totalHours: "Total hours",
      isActive: "Is active",
      createdAt: "Created at",
      updatedAt: "Updated at",
      contractStartDate: "Contract Date",
    },
    errors: {
      nameRequired: "Name is required",
      createFailed: "Could not create service",
      updateFailed: "Could not update service",
      deleteFailed: "Could not delete service",
    },
    messages: {
      created: "Service created",
      updated: "Service updated",
      deleted: "Service deleted",
    },
  },

  /* --- NOTES (NEW) --- */
  notes: {
    title: "Notes Management",
    list: {
      title: "Notes",
      add: "Add Note",
      searchPlaceholder: "Search notes...",
      headers: {
        name: "Name",
        description: "Description",
        amount: "Amount",
        totalAmount: "Total Amount",
        clients: "Clients",
        properties: "Properties",
        guards: "Guards",
        services: "Services",
        shifts: "Shifts",
        weapons: "Weapons",
        typeOfServices: "Type(s) of Service",
        viewedBy: "Viewed by",
        actions: "Actions",
      },
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
    },
    create: {
      title: "Create Note",
      addAmount: "Add amount",
      addAmountAria: "Add new amount entry",
      removeAmountAria: "Remove amount entry",
      amountPlaceholder: "e.g. 100.50 or -15",
      amountsHelp: "You can add multiple amounts (positive or negative). They will be summed and the final total sent to the backend.",
      totalLabel: "Total",
      fields: {
        name: "Name",
        description: "Description",
        amounts: "Amounts",
        clients: "Clients",
        properties: "Properties",
        guards: "Guards",
        services: "Services",
        shifts: "Shifts",
        weapons: "Weapons",
        type_of_services: "Type of Service",
      },
      buttons: {
        add: "Add",
        create: "Create",
        creating: "Creating...",
        addAmount: "+ Add amount",
        removeAmount: "− Remove",
      },
      validation: {
        nameRequired: "Name is required",
        amountInvalid: "Amount must be a valid number",
      },
      messages: {
        created: "Note created",
      },
      help: {
        amountsSummary: "Example: adding 15, -15, 25 results in total 25 (that is what will be sent to the backend).",
      },
    },
    edit: {
      title: "Edit Note",
      save: "Save",
      saving: "Saving...",
    },
    delete: {
      title: "Delete Note",
      confirm: "Are you sure you want to delete note \"{name}\"?",
    },
    errors: {
      loadFailed: "Could not load notes",
      createFailed: "Could not create note",
      updateFailed: "Could not update note",
      deleteFailed: "Could not delete note",
    },
    messages: {
      updated: "Note updated",
      deleted: "Note deleted",
    },
  },

  dashboard: {
    title: "Dashboard",
    kpis: {
      clients: "Clients",
      activeClients: "active",
      properties: "Properties",
      registeredTotal: "Registered in total",
      guards: "Guards",
      inService: "In service",
      monthlyRevenue: "Monthly Revenue",
      currentEstimate: "Current estimate",
      fuelCost: "Fuel Cost",
      thisMonth: "This month",
      guardSalaries: "Guard Salaries",
      projected: "Projected"
    },
    chartHoursTitle: "Working Hours by Guard",
    chartCostsTitle: "Cost Analysis",
    series: {
      priceTotal: "Total Price",
      fuelCost: "Fuel Cost",
      guardSalary: "Guard Salary",
    },
    upcomingShifts: {
      title: "Upcoming Shifts",
      headers: {
        guard: "Guard",
        location: "Location",
        date: "Date",
        schedule: "Schedule",
      },
      noShifts: "No upcoming shifts scheduled",
    },
    tabs: {
      overview: "Overview",
      timeline: "Timeline",
      advanced: "Advanced Metrics",
      reports: "Reports",
    },
    metrics: {
      operational: {
        title: "📊 Operational Metrics",
        activeGuards: "Active Guards",
        guardsOnDuty: "on duty now",
        shiftsThisMonth: "Shifts This Month",
        attendance: "attendance",
        overtime: "Overtime",
        averageShift: "avg per shift",
      },
      financial: {
        title: "💰 Financial Metrics",
        monthlyRevenue: "Monthly Revenue",
        margin: "Margin",
        costPerHour: "Cost per Hour",
        perGuard: "/guard",
        pendingPayments: "Pending Payments",
        overdue: "overdue",
        revenuePerProperty: "Revenue per Property",
        monthlyAverage: "Monthly average",
      },
      security: {
        title: "🛡️ Security Metrics",
        incidentsThisMonth: "Incidents This Month",
        vsLastMonth: "vs Last Month",
        responseTime: "Response Time",
        incidentsResolved: "incidents resolved",
        preventionScore: "Prevention Score",
        highPriority: "high priority",
      },
      efficiency: {
        title: "⚡ Efficiency Metrics",
        propertyUtilization: "Property Utilization",
        fullCoverage: "Full Coverage",
        guardEfficiency: "Guard Efficiency",
        productiveTime: "Productive time",
        clientSatisfaction: "Client Satisfaction",
        evaluationAverage: "Evaluation average",
        renewalRate: "Renewal Rate",
        contractsRenewed: "Contracts renewed",
      },
    },
    reports: {
      title: "📊 Reports and Analysis",
      monthlyOperations: {
        title: "Monthly Operations Report",
        description: "Complete summary of month activities",
      },
      incidentAnalysis: {
        title: "Incident Analysis",
        description: "Security trends and patterns",
      },
      financialReport: {
        title: "Financial Report",
        description: "Revenue, expenses and profitability",
      },
      guardPerformance: {
        title: "Guard Performance",
        description: "Staff evaluation and metrics",
      },
      clientSatisfaction: {
        title: "Client Satisfaction",
        description: "Surveys and feedback",
      },
      geographicAnalysis: {
        title: "Geographic Analysis",
        description: "Distribution and coverage by zones",
      },
    },
  },
} as const;
