export const EN_TEXT = {
  appName: "Texas Counties Division Patrol LLC",
  header: {
    notificationsAria: "Notifications",
    userMenuAria: "Toggle user menu",
  },
  sidebar: {
    navigationLabel: "Navigation",
  },
  menu: {
    dashboard: "Dashboard",
    clients: "Clients",
    guards: "Guards",
    users: "Users",
    properties: "Properties",
  },

  pagination: {
    goToPlaceholder: "Go to...",
    ariaFirst: "Go to first page",
    ariaPrev: "Previous page",
    ariaNext: "Next page",
    ariaLast: "Go to last page",
    inputAriaLabel: "Go to specific page",
    pageInfo: "{current} of {total}",
  },

  common: {
    notFoundTitle: "Content not found",
    notFoundDescription: "Select an option from the menu.",
  },
  actions: {
    refresh: "Refresh",
    save: "Save",
    cancel: "Cancel",
  },
  dashboard: {
    title: "Dashboard Overview",
    chartHoursTitle: "Hours worked per month",
    chartCostsTitle: "Costs per month",
    series: {
      priceTotal: "Total Price",
      fuelCost: "Fuel Cost",
      guardSalary: "Guard Salary",
    },
    upcomingShifts: {
      title: "Upcoming shifts",
      headers: { guard: "Guard", location: "Location", date: "Date" },
    },
  },

  clients: {
    title: "Clients Management",
    table: {
      title: "Clients List",
      add: "Add",
      headers: {
        name: "Name",
        properties: "# Properties",
        totalPrice: "Total Price ($)",
        expenses: "Expenses ($)",
        fuel: "Fuel ($)",
        actions: "Actions",
      },
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
    },
    list: {
      title: "Clients List",
      addClient: "Add Client",
      searchPlaceholder: "Search clients...",
      headers: {
        clientName: "Client Name",
        email: "Email",
        phone: "Phone",
        balance: "Balance",
        status: "Status",
        actions: "Actions",
      },
      statusActive: "Active",
      statusInactive: "Inactive",
    },
    properties: {
      title: "Properties of {clientName}",
      headers: {
        name: "Name",
        price: "Price ($)",
        expenses: "Expenses ($)",
        hours: "Hours/Month",
        fuel: "Fuel ($)",
        actions: "Actions",
      },
      pageSizeLabel: "Rows per page",
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
    },
    loading: "Loading clients...",
    selectPrompt: "Select a client to view its properties.",
    propertiesLoading: "Loading properties...",
    errorLoading: "Error loading clients",
    propertiesError: "Error loading properties",
  },

  properties: {
    title: "Properties Management",
    table: {
      title: "Properties List",
      add: "Add",
      searchPlaceholder: "Search properties...",
      headers: {
        alias: "Alias",
        name: "Name",
        address: "Address",
        serviceTypes: "Service Types",
        monthlyRate: "Monthly Rate",
        totalHours: "Total Hours",
        actions: "Actions",
      },
      pageSizeLabel: "Rows per page",
      actionEdit: "Edit {name}",
      actionDelete: "Delete {name}",
    },
    form: {
      editTitle: "Edit Property",
      createTitle: "Create Property",
      fields: {
        ownerUser: "Owner (user id)",
        ownerPhone: "Owner phone",
        name: "Name",
        alias: "Alias",
        address: "Address",
        typesOfService: "Service Types",
        monthlyRate: "Monthly Rate",
        contractStartDate: "Contract Start Date",
        totalHours: "Total Hours",
      },
      placeholders: {
        owner: "Search client by name/username...",
        name: "Property name",
        alias: "Alias or alternative name",
        address: "Property address",
        monthlyRate: "$0.00",
        totalHours: "0",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
        save: "Save",
        saving: "Saving...",
        delete: "Delete",
      },
      searchingText: "Searching...",
      noResultsText: "No results",
      ownerHelp: "Select the owner client. Backend will receive the client id.",
      serviceTypesTitle: "Service Types",
      loadingTypesText: "Loading service types",
      noTypesText: "No types available",
      success: "Property updated",
      /**
       * New key used after creating a property
       */
      createSuccess: "Property created successfully",
      errorUpdate: "Error updating property",
      errorRefresh: "Failed to refresh properties",
      delete: {
        title: "Delete Property",
        confirm: "Are you sure you want to delete {name}?",
        note: "This action cannot be undone.",
        button: "Delete",
        deleting: "Deleting...",
        success: "Property deleted successfully",
        error: "Error deleting property",
        cancel: "Cancel",
        errorRefresh: "Failed to refresh properties",
      },
    },
  },

  guards: {
    title: "Guards Management",
    selectPrompt: "Select a guard to view their shifts.",
    weeklyMaxNote: "Note: totals are calculated by summing shifts (hours × pricePerHour). Weekly max set to {hours}h.",
    table: {
      title: "Guards List",
      add: "Add Guard",
      headers: {
        name: "Name",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone",
        ssn: "SSN / ID",
        birthdate: "Birthdate",
        totalHours: "Total Hours",
        totalSalary: "Total Salary ($)",
        actions: "Actions",
      },
      ssnHidden: "******",
      pageSizeLabel: "Rows per page",
      actionEdit: "Edit guard {name}",
      actionDeleteConfirm: "Delete guard {name}?",
      actionDelete: "Delete guard {name}",
      confirmLabel: "Confirm",
      deleteSuccess: "Guard {name} deleted",
    },
    errorLoading: "Error loading guards",
    form: {
      createTitle: "Create Guard",
      editTitle: "Edit Guard",
      fields: {
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone",
        ssn: "SSN / ID",
        birthdate: "Birthdate",
        address: "Address",
      },
      validation: {
        invalidEmail: "Invalid email",
        firstNameRequired: "First name is required",
        lastNameRequired: "Last name is required",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        creating: "Creating...",
        save: "Save",
        saving: "Saving...",
        delete: "Delete",
      },
    },
  },

  users: {
    title: "User Management",
    editTitle: "Edit User",
    saveChanges: "Save changes",
    cancel: "Cancel",
    loading: "Loading users...",
    selectPrompt: "Select a user to view and edit their permissions.",
    noPermissions: "No permissions",
    permissionsTitle: "Permissions by resource",
    userTypes: {
      superuser: "Superuser",
      staff: "Staff",
      user: "User",
    },
    accessTypes: {
      viewer: "Viewer",
      manager: "Manager",
      admin: "Admin",
    },
    table: {
      title: "Users List",
      add: "Add User",
      searchPlaceholder: "Search...",
      perPage: "per page",
      headers: {
        username: "Username",
        firstName: "First name",
        lastName: "Last name",
        email: "Email",
        permissions: "Permissions",
        actions: "Actions",
      },
    },
    form: {
      createTitle: "Create User",
      editTitle: "Edit User",
      fields: {
        username: "Username",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
      },
      validation: {
        usernameRequired: "Username is required",
        firstNameRequired: "First name is required",
        lastNameRequired: "Last name is required",
        emailRequired: "Email is required",
        emailInvalid: "Invalid email format",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 6 characters",
        passwordMatch: "Passwords do not match",
      },
      buttons: {
        cancel: "Cancel",
        create: "Create",
        save: "Save",
        saving: "Saving...",
      },
    },
    errors: {
      loadingPermissions: "Error loading permissions/user",
      grantingPermissions: "Error granting permissions",
      revokingPermissions: "Error revoking permissions",
    },
  },

  accountMenu: {
    language: "Language",
    english: "English",
    spanish: "Español",
    settings: "Settings",
    support: "Support",
    logout: "Logout",
  },

  logoutDialog: {
    title: "Confirm logout",
    description: "Are you sure you want to log out? You will need to sign in again to access the dashboard.",
    cancel: "Cancel",
    confirm: "Logout",
    successToast: "Logged out successfully",
  },

  login: {
    title: "Login",
    description: "Enter your username and password to access your account.",
    usernameLabel: "Username",
    usernamePlaceholder: "username",
    passwordLabel: "Password",
    submit: "Sign in",
    submitting: "Signing in...",
    errorDefault: "Invalid credentials. Please try again.",
  },
} as const;
