export const ES_TEXT = {
  appName: "Texas Counties Division Patrol LLC",
  header: {
    notificationsAria: "Notificaciones",
    userMenuAria: "Abrir menú de usuario",
  },
  sidebar: {
    navigationLabel: "Navegación",
  },
  menu: {
    dashboard: "Panel",
    clients: "Clientes",
    guards: "Guardias",
    users: "Usuarios",
  properties: "Propiedades",
  shifts: "Turnos",
  },

  pagination: {
    goToPlaceholder: "Ir a...",
    ariaFirst: "Ir a la primera página",
    ariaPrev: "Página anterior",
    ariaNext: "Página siguiente",
    ariaLast: "Ir a la última página",
    inputAriaLabel: "Ir a página específica",
    pageInfo: "{current} de {total}",
  },

  table: {
    noMatch: "No hay coincidencias",
    noResults: "No se encontraron resultados para \"{search}\"",
    noData: "No hay datos disponibles",
    items: "elementos", // <--- agregado
  },

  common: {
    notFoundTitle: "Contenido no encontrado",
    notFoundDescription: "Selecciona una opción del menú.",
    loading: "Cargando...",
  },

  actions: {
    refresh: "Actualizar",
    save: "Guardar",
    cancel: "Cancelar",
    cancelEdit: "Cancelar edición",
    edit: "Editar",
    delete: "Eliminar",
    reset: "Restaurar",
    close: "Cerrar",
    actions: "Acciones",
    create: "Crear",
    copy: "Copiar",
    copySuccess: "Copiado al portapapeles",
    copyError: "No se pudo copiar",
    saving: "Guardando...",
    deleting: "Eliminando...",
    view: "Ver", // <--- agregado
  },

  clients: {
    title: "Gestión de Clientes",
    table: {
      title: "Lista de Clientes",
      add: "Agregar",
      headers: {
        name: "Nombre",
        properties: "# Propiedades",
        totalPrice: "Precio Total ($)",
        expenses: "Gastos ($)",
        fuel: "Gasolina ($)",
        actions: "Acciones",
      },
      actionEdit: "Editar {name}",
      actionDelete: "Eliminar {name}",
    },
    list: {
      title: "Lista de Clientes",
      addClient: "Agregar Cliente",
      searchPlaceholder: "Buscar clientes...",
      headers: {
        clientName: "Nombre del Cliente",
        email: "Correo",
        phone: "Teléfono",
        balance: "Balance",
        status: "Estado",
        actions: "Acciones",
      },
      statusActive: "Activo",
      statusInactive: "Inactivo",
    },

    form: {
      createTitle: "Crear Cliente",
      fields: {
        username: "Usuario",
        firstName: "Nombre *",
        lastName: "Apellido *",
        email: "Correo *",
        phone: "Teléfono",
        address: "Dirección",
        billingAddress: "Dirección de facturación",
      },
      placeholders: {
        address: "Dirección principal del cliente",
        billingAddress: "Dirección usada para facturación",
      },
      buttons: {
        cancel: "Cancelar",
        create: "Crear",
        creating: "Creando...",
      },
      validation: {
        firstNameRequired: "El nombre es requerido",
        lastNameRequired: "El apellido es requerido",
        emailRequired: "El correo es requerido",
      },
      success: "Cliente creado",
    },

    properties: {
      title: "Propiedades de {clientName}",
      headers: {
        name: "Nombre",
        price: "Precio ($)",
        expenses: "Gastos ($)",
        hours: "Horas/Mes",
        fuel: "Gasolina ($)",
        actions: "Acciones",
      },
      pageSizeLabel: "Filas por página",
      actionEdit: "Editar {name}",
      actionDelete: "Eliminar {name}",
    },
    loading: "Cargando clientes...",
    selectPrompt: "Selecciona un cliente para ver sus propiedades.",
    propertiesLoading: "Cargando propiedades...",
    errorLoading: "Error al cargar clientes",
    propertiesError: "Error al cargar propiedades",
  },

  properties: {
    title: "Gestión de Propiedades",
    table: {
      title: "Lista de Propiedades",
      add: "Agregar",
      searchLabel: "Buscar propiedades",
      searchPlaceholder: "Buscar propiedades...",
      headers: {
        owner: "Propietario",
        alias: "Alias",
        name: "Nombre",
        address: "Dirección",
        serviceTypes: "Tipos de servicio",
        monthlyRate: "Tarifa Mensual",
        totalHours: "Horas",
        actions: "Acciones",
      },
      pageSizeLabel: "Filas por página",
      actionEdit: "Editar {name}",
      actionDelete: "Eliminar {name}",
    },
    form: {
      editTitle: "Editar Propiedad",
      createTitle: "Crear Propiedad",
      fields: {
        ownerUser: "Propietario ",
        ownerPhone: "Teléfono propietario",
        name: "Nombre",
        alias: "Alias",
        address: "Dirección",
        typesOfService: "Tipos de Servicio",
        monthlyRate: "Tarifa Mensual",
        contractStartDate: "Fecha de Inicio del Contrato",
        totalHours: "Horas",
      },
      placeholders: {
        owner: "Buscar cliente por nombre/username...",
        name: "Nombre de la propiedad",
        alias: "Alias o nombre alternativo",
        address: "Dirección de la propiedad",
        monthlyRate: "$0.00",
        totalHours: "0",
      },
      buttons: {
        cancel: "Cancelar",
        create: "Crear",
        creating: "Creando...",
        save: "Guardar",
        saving: "Guardando...",
        delete: "Eliminar",
      },
      searchingText: "Buscando...",
      noResultsText: "No hay resultados",
      ownerHelp: "Selecciona el cliente propietario. El backend recibirá el id del cliente.",
      serviceTypesTitle: "Tipos de servicio",
      loadingTypesText: "Cargando tipos de servicio",
      noTypesText: "No hay tipos disponibles",
      success: "Propiedad actualizada",
      createSuccess: "Propiedad creada exitosamente",
      errorUpdate: "Error actualizando propiedad",
      errorRefresh: "Error al refrescar propiedades",
      delete: {
        title: "Eliminar Propiedad",
        confirm: "¿Estás seguro que quieres eliminar {name}?",
        note: "Esta acción no se puede deshacer.",
        button: "Eliminar",
        deleting: "Eliminando...",
        success: "Propiedad eliminada exitosamente",
        error: "Error eliminando propiedad",
        cancel: "Cancelar",
        errorRefresh: "Error al refrescar propiedades",
      },
      viewer: "Visor",
      editor: "Editor",
      admin: "Admin",
      full: "Completo",
    },
    help: "Marcar para otorgar, desmarcar para revocar.",
  },

  guards: {
    title: "Gestión de Guardias",
    selectPrompt: "Selecciona un guardia para ver sus turnos.",
    weeklyMaxNote: "Nota: los totales se calculan sumando los turnos (hours × pricePerHour). Máximo semanal configurado a {hours}h.",
    table: {
      title: "Lista de Guardias",
      add: "Agregar Guardia",
      addButton: "Agregar Guardia",
      searchPlaceholder: "Buscar guardias...",
      headers: {
        name: "Nombre",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Email",
        phone: "Teléfono",
        ssn: "DNI / SSN",
        birthdate: "Fecha Nac.",
        totalHours: "Horas",
        totalSalary: "Salario Total ($)",
        actions: "Acciones",
      },
      ssnHidden: "******",
      pageSizeLabel: "Filas por página",
      actionEdit: "Editar guardia {name}",
      actionDeleteConfirm: "¿Eliminar guardia {name}?",
      actionDelete: "Eliminar guardia {name}",
      confirmLabel: "Confirmar",
      deleteSuccess: "Guardia {name} eliminado",
    },
    errorLoading: "Error al cargar guardias",
    form: {
      createTitle: "Crear Guardia",
      editTitle: "Editar Guardia",
      fields: {
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Email",
        phone: "Teléfono",
        ssn: "DNI / SSN",
        birthdate: "Fecha de Nacimiento",
        address: "Dirección",
      },
      validation: {
        invalidEmail: "Correo inválido",
        firstNameRequired: "Nombre es requerido",
        lastNameRequired: "Apellido es requerido",
      },
      buttons: {
        cancel: "Cancelar",
        create: "Crear",
        creating: "Creando...",
        save: "Guardar",
        saving: "Guardando...",
        delete: "Eliminar",
      },
      actions: {
        cancel: "Cancelar",
        create: "Crear",
        creating: "Creando...",
        save: "Guardar",
        saving: "Guardando...",
        delete: "Eliminar",
        showSsn: "Mostrar"
      }
    },
    tariffs: {
      title: "Tarifas de {name}",
      assignedLabel: "Tarifas asignadas",
      assignedNote: "Una tarifa por propiedad. Haz click para editar.",
      count: "{count} propiedad(es) con tarifa",
      empty: "Este guard no tiene tarifas asignadas.",
      rateHeader: "Tarifa",
      activeHeader: "Activo",
      flag: "⚑ Tarifa",
      active: "Activo",
      inactive: "Inactivo",
      selectedPropertyLabel: "Propiedad seleccionada",
      noneSelected: "Ninguna propiedad seleccionada",
      rateLabel: "Tarifa por hora",
      ratePlaceholder: "Ej: 15.00",
      activeLabel: "Activo",
      changeProperty: "Cambiar propiedad",
      create: "Crear tarifa",
      update: "Actualizar tarifa",
      saving: "Guardando...",
      note: "Nota: si la propiedad ya tiene tarifa, al seleccionarla pasarás a editarla; si no, crearás una nueva.",
      validation: {
        propertyRequired: "Selecciona una propiedad primero",
        rateRequired: "La tarifa es requerida",
        rateInvalid: "La tarifa debe ser un número válido",
        rateNegative: "La tarifa no puede ser negativa",
        rateTooHigh: "La tarifa no puede ser mayor a $1000"
      },
      actions: {
        create: "crear",
        update: "actualizar"
      },
      confirmSave: "¿Estás seguro de {action} esta tarifa de ${rate} para {property}?",
      confirmCancelEdit: "¿Estás seguro de cancelar la edición? Se perderán los cambios no guardados.",
      confirmDelete: "¿Estás seguro de eliminar la tarifa para {property}?",
      exists: "Ya existe una tarifa para esta propiedad. Se cargará para editar.",
      createSuccess: "Tarifa creada exitosamente",
      updateSuccess: "Tarifa actualizada exitosamente",
      deleteSuccess: "Tarifa eliminada exitosamente",
      saveError: "Error guardando tarifa. Verifica los datos e intenta nuevamente.",
      deleteError: "Error eliminando tarifa. Intenta nuevamente."
    },
  },

  users: {
    title: "Gestión de Usuarios",
    editTitle: "Editar Usuario",
    saveChanges: "Guardar cambios",
    cancel: "Cancelar",
    loading: "Cargando usuarios...",
    selectPrompt: "Selecciona un usuario para ver y editar sus permisos.",
    noPermissions: "Sin permisos",
    permissionsTitle: "Permisos por recurso",
    userTypes: {
      superuser: "Superusuario",
      staff: "Staff",
      user: "Usuario",
    },
    accessTypes: {
      viewer: "Visor",
      manager: "Gerente",
      admin: "Administrador",
    },
    table: {
      title: "Lista de Usuarios",
      add: "Agregar Usuario",
      searchPlaceholder: "Buscar...",
      perPage: "por página",
      headers: {
        username: "Usuario",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo",
        permissions: "Estado",
        actions: "Acciones",
      },
    },
    form: {
      createTitle: "Crear Usuario",
      editTitle: "Editar Usuario",
      fields: {
        username: "Usuario",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo",
        password: "Contraseña",
        confirmPassword: "Confirmar Contraseña",
      },
      validation: {
        usernameRequired: "Usuario es requerido",
        firstNameRequired: "Nombre es requerido",
        lastNameRequired: "Apellido es requerido",
        emailRequired: "Email es requerido",
        emailInvalid: "Email inválido",
        passwordRequired: "Contraseña es requerida",
        passwordMin: "La contraseña debe tener al menos 6 caracteres",
        passwordMatch: "Las contraseñas no coinciden",
      },
      buttons: {
        cancel: "Cancelar",
        create: "Crear",
        creating: "Creando...",
        save: "Guardar",
        saving: "Guardando...",
        delete: "Eliminar",
      },
      createSuccess: "Usuario creado",
    },
    permissionsHelp: "Los permisos se aplican como resource.action.",
  },

  permissions: {
    resources: {
      guard: { label: "Guardia" },
      expense: { label: "Gasto" },
      shift: { label: "Turno" },
      client: { label: "Cliente" },
    },
    actions: {
      create: "Crear",
      read: "Leer",
      update: "Actualizar",
      delete: "Eliminar",
      approve: "Aprobar",
      assign: "Asignar",
    },
  },

  accountMenu: {
    language: "Idioma",
    english: "Inglés",
    spanish: "Español",
    settings: "Configuración",
    support: "Soporte",
    logout: "Cerrar sesión",
  },

  logoutDialog: {
    title: "Confirmar cierre de sesión",
    description: "¿Estás seguro de que quieres cerrar sesión? Tendrás que iniciar sesión nuevamente para acceder al panel.",
    cancel: "Cancelar",
    confirm: "Cerrar sesión",
    successToast: "Sesión cerrada exitosamente",
  },

  login: {
    title: "Iniciar sesión",
    description: "Ingresa tu usuario y contraseña para acceder a tu cuenta.",
    usernameLabel: "Usuario",
    usernamePlaceholder: "usuario",
    passwordLabel: "Contraseña",
    submit: "Iniciar sesión",
    submitting: "Iniciando sesión...",
    errorDefault: "Credenciales inválidas. Por favor intenta de nuevo.",
  },

  // ------------- SHIFTS -------------
  shifts: {
    create: {
      title: "Crear Turno",
      propertyPlaceholder: "ID de propiedad (número)",
    },
    edit: {
      title: "Editar Turno",
    },
    delete: {
      title: "Eliminar Turno",
      confirm: "¿Estás seguro que quieres eliminar este turno?",
      hardDeleteLabel: "Eliminar permanentemente (hard delete)",
    },
    show: {
      title: "Detalles del Turno",
      subtitle: "Lista de turnos (scrollable)", // <--- agregado
      open: "Ver turnos", // <--- agregado
    },
    errors: {
      missingDates: "Fecha de inicio y fin son requeridas",
      endBeforeStart: "La fecha de fin debe ser posterior a la de inicio",
      missingProperty: "ID de propiedad requerido",
      missingGuard: "ID de guardia requerido",
      createFailed: "No se pudo crear el turno",
      fetchFailed: "No se pudo cargar el turno",
      updateFailed: "No se pudo actualizar el turno",
      deleteFailed: "No se pudo eliminar el turno",
      noShift: "No hay turno cargado",
    },
    messages: {
      created: "Turno creado",
      updated: "Turno actualizado",
      deleted: "Turno eliminado",
      softDeleted: "Turno eliminado (soft)",
    },
  },

  dashboard: {
    title: "Panel de Control",
    kpis: {
      clients: "Clientes",
      activeClients: "activos",
      properties: "Propiedades", 
      registeredTotal: "Registradas en total",
      guards: "Guardias",
      inService: "En servicio",
      monthlyRevenue: "Ingresos Mensuales",
      currentEstimate: "Estimado actual",
      fuelCost: "Costo Combustible",
      thisMonth: "Este mes",
      guardSalaries: "Salarios Guardias",
      projected: "Proyectados"
    },
    chartHoursTitle: "Horas de Trabajo por Guardia",
    chartCostsTitle: "Análisis de Costos",
    series: {
      priceTotal: "Precio Total",
      fuelCost: "Costo de Combustible",
      guardSalary: "Salario de Guardia",
    },
    upcomingShifts: {
      title: "Próximos Turnos",
      headers: {
        guard: "Guardia",
        location: "Ubicación",
        date: "Fecha",
        schedule: "Horario",
      },
      noShifts: "No hay turnos próximos programados",
    },
    tabs: {
      overview: "Resumen",
      timeline: "Timeline",
      advanced: "Métricas Avanzadas",
      reports: "Reportes",
    },
    metrics: {
      operational: {
        title: "📊 Métricas Operacionales",
        activeGuards: "Guardias Activos",
        guardsOnDuty: "en servicio",
        shiftsThisMonth: "Turnos Este Mes",
        attendance: "asistencia",
        overtime: "Horas Extra",
        averageShift: "promedio por turno",
        onDuty: "En servicio",
        totalShifts: "Turnos Totales",
        thisWeek: "Esta semana",
        propertyCount: "Propiedades",
        underSurveillance: "Bajo vigilancia",
        upcomingShifts: "Próximos Turnos",
        scheduled: "Programados",
      },
      financial: {
        title: "💰 Métricas Financieras",
        monthlyRevenue: "Ingresos Mensuales",
        margin: "Margen",
        costPerHour: "Costo por Hora",
        perGuard: " por guardia",
        pendingPayments: "Pagos Pendientes",
        overdue: "vencido",
        revenuePerProperty: "Ingresos por Propiedad",
        monthlyAverage: "Promedio mensual",
        estimated: "Estimados",
        operationalCosts: "Costos Operacionales",
        thisMonth: "Este mes",
        profitMargin: "Margen de Ganancia",
        netMargin: "Margen neto",
        averageContractValue: "Valor Promedio de Contrato",
        perProperty: "Por propiedad",
      },
      security: {
        title: "🛡️ Métricas de Seguridad",
        incidentsThisMonth: "Incidentes Este Mes",
        vsLastMonth: "vs mes anterior",
        responseTime: "Tiempo de Respuesta",
        incidentsResolved: "incidentes resueltos",
        preventionScore: "Score de Prevención",
        highPriority: "alta prioridad",
      },
      efficiency: {
        title: "⚡ Métricas de Eficiencia",
        propertyUtilization: "Utilización de Propiedades",
        fullCoverage: "Cobertura completa",
        guardEfficiency: "Eficiencia de Guardias",
        productiveTime: "Tiempo productivo",
        clientSatisfaction: "Satisfacción del Cliente",
        evaluationAverage: "Promedio de evaluaciones",
        renewalRate: "Tasa de Renovación",
        contractsRenewed: "Contratos renovados",
      },
    },
    reports: {
      title: "📋 Reportes Disponibles",
      monthlyOperations: {
        title: "Operaciones Mensuales",
        description: "Resumen completo de actividades del mes",
      },
      incidentAnalysis: {
        title: "Análisis de Incidentes",
        description: "Estadísticas y tendencias de seguridad",
      },
      financialReport: {
        title: "Reporte Financiero",
        description: "Estado de ingresos, costos y rentabilidad",
      },
      guardPerformance: {
        title: "Rendimiento de Guardias",
        description: "Evaluación de productividad y desempeño",
      },
      clientSatisfaction: {
        title: "Satisfacción de Clientes",
        description: "Feedback y evaluaciones de servicio",
      },
      geographicAnalysis: {
        title: "Análisis Geográfico",
        description: "Distribución y cobertura territorial",
      },
    },
  },
} as const;
